### ISSUE TITLE
Failed to send file as document, server response is 400

### ISSUE THREAD

**Issue by denzen84** [smartnode/telebot#16]
`ret = telebot_send_document(handle, sstgbconf.user_id, sstgbconf.docfile, true, false, 0, NULL);
        if (ret != TELEBOT_ERROR_NONE) {
                printf("Failed to send document: %d \n", ret);
        }`

The result is:

**[ERROR][telebot_core_curl_perform:95]Wrong HTTP response received, response: 400
Failed to send document: -1**

Possibly changes in Telegram API ?

**Comment by denzen84** [comment]
Full source code of the bot available: [https://github.com/denzen84/sstgb](url)

**Comment by smartnode** [comment]
Does it fail only with sending document? Or everything else (message, video)?

**Comment by denzen84** [comment]
It fails only with sending documents. I tried different types (text, pdf, jpg, mp4 ...). Sending text messages, images and videos works fine.

**Comment by denzen84** [comment]
So, I found i fix this bug:

**telebot-core.c**: line 456:
`return telebot_core_curl_perform(core_h, TELEBOT_METHOD_SEND_DOCUMENT, post);`

there was method _TELEBOT_METHOD_SEND_PHOTO_ instead of _TELEBOT_METHOD_SEND_DOCUMENT_.

**Comment by denzen84** [comment]
Please update master branch :)

**Comment by smartnode** [comment]
Thanks for the bug fix. You may also pull request.
