### ISSUE TITLE
Possible deadlock in telebot-core.telebot_core_curl_perform()

### ISSUE THREAD

**Issue by Nik4053** [smartnode/telebot#31]
The method sets core_h->busy = true, but never sets it back to false on error.
 -> Next time program will halt indefinitely.

**Comment by smartnode** [comment]
Indeed, there is a bug that may cause deadlock. Following patch fixes it.
https://github.com/smartnode/telebot/commit/e4adb7189d57dc88d1f7aaba28d957122555eff0

**Comment by Nik4053** [comment]
I am new to this kind of thing but why can we use just a normal variable as a lock?
 I thought a mutex or an atomic operation has to be used in such cases.

**Comment by smartnode** [comment]
I was using simpler alternative to mutex, and remove necessity for locking, and/or busy waiting.
