### ISSUE TITLE
Bot crashes when two identic messages were sent in a row

### ISSUE THREAD

**Issue by pavel-the-best** [smartnode/telebot#38]
I use example, provided in echobot.c.
When I try to send two identic messages ("abcd" or "test") in a row bot crashes with following error:
```
corrupted size vs. prev_size while consolidating
[1]    60895 abort (core dumped)    ./echobot
```

My environment;
```
$ uname -a
Linux ppc 5.4.38-gentoo #21 SMP Wed Jul 22 21:10:25 MSK 2020 x86_64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz GenuineIntel GNU/Linux
```

**Comment by smartnode** [comment]
I think you have already fixed with https://github.com/smartnode/telebot/pull/39
