### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by arydevy** [smartnode/telebot#42]
so i want to make a tg bot with this lib but i dont find any biginer frendly spreedsheet or exemple i dont understand the lib

**Comment by wmealing** [comment]
On the right hand side .. see https://elmurod.net/telebot/

**Comment by arydevy** [comment]
but i dont understand the code!

**Comment by arydevy** [comment]
but i dont understand the code!

**Comment by wmealing** [comment]
If you're more comfortable with python, you could start with getting a telegram bot working with this project: https://github.com/python-telegram-bot/python-telegram-bot

**Comment by pavel-the-best** [comment]
You won't be able to make a telegram bot with this library if you don't understand C code

**Comment by arydevy** [comment]
i understand c but i dont understand the lib

**Comment by arydevy** [comment]
i understand c but i dont understand the lib

**Comment by jack23247** [comment]
I think @arydevy is trying to state that the example given does not clearly explain how to set up a bot unless you have prior experience with Telegram's Bot API: a more well-documented section of code, or even a flowchart explaining how the various functions of the API cooperate would be useful for people trying to create a bot for the first time using this library.

**Comment by arydevy** [comment]
i made a bot for tg in python with another sdk this is diferent
you are right @jack23247
