### ISSUE TITLE
make install would be nice

### ISSUE THREAD

**Issue by pjalocha** [smartnode/telebot#52]
so the API canbe installed and used in an universal way from other applications.

**Comment by smartnode** [comment]
since build is based on CMake, make install works out of box. Run as below.
```sh
mkdir -p Build && cd Build
cmake ../
make install
```

**Comment by pjalocha** [comment]
But with me it says it can not find the telebot.pc file, so what could be missing here ?

CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/xxxxxxx/telebot/telebot.pc".

**Comment by pjalocha** [comment]
I just tried on another system and it is the same, before I only tried on my RPI, any idea what could it be ?

[ 90%] Building C object test/CMakeFiles/echobot.dir/echobot.c.o
[100%] Linking C executable echobot
make[2]: Leaving directory '/home/pawel/telebot/build'
[100%] Built target echobot
make[1]: Leaving directory '/home/pawel/telebot/build'
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find "/home/pawel/telebot/telebot.pc": No such file or
  directory.

**Comment by pjalocha** [comment]
Thank you, it worked this time !
