### ISSUE TITLE
disable_notification is not working ?

### ISSUE THREAD

**Issue by pjalocha** [smartnode/telebot#54]
It seems the notification sound is always there and the disable_notification is not present in the JSON debug printout ?
Or did I miss something ?
There seems to be a code treating it in the telebot-core_send-message() but then why it does not work ?

**Comment by smartnode** [comment]
I'm sure `telebot_core_send_message()` does add disable_notification as post data but I'm not sure why it would not work. If you can analyze more and provide what is the bug we can fix it.
