### ISSUE TITLE
More Extensive Documentation?

### ISSUE THREAD

**Issue by samuel-allan** [smartnode/telebot#8]
So far for me the header files are sufficient, but I was wondering whether it would be worth creating a Wiki page to get new users started? I was also wondering whether the ability to display a couple of clickable options to the user is implemented (obviously this exposes how new I am to the telegram bot api in general).

Thank you very much for this effort!
The API framework appears pretty robust and stable so far

**Comment by smartnode** [comment]
Hello Samuel Alan, 
Thanks for suggestion but due to my own work. I am not able to work on this project.
There are number of better alternatives in C++. 
However, if you would like to write it Wiki you would be more thank welcome.
Thanks.
